name: Code Quality
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    name: Check types, format, and lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Check types
        run: npm run types
      - name: Run prettier
        run: npm run prettier
      - name: Run next lint
        run: npm run lint
